# from galaxy
- src: geerlingguy.security
  version: 1.5.0

- src: zzet.rbenv
  version: 3.0.0

- src: jdauphant.nginx
  version: v2.8.1

- src: coopdevs.certbot_nginx
  version: 0.0.1

- src: oefenweb.swapfile
  version: v2.0.7

- src: Datadog.datadog
  version: 2.4.0
