# from galaxy
- src: geerlingguy.security
  version: 1.5.0

- src: zzet.rbenv
  version: 3.4.2

- src: jdauphant.nginx
  version: v2.8.1

- src: coopdevs.certbot_nginx
  version: 0.0.4

- src: oefenweb.swapfile
  version: v2.0.14

- src: Datadog.datadog
  version: 2.4.0

- src: geerlingguy.postgresql
  version: 1.4.5

- src: libre_ops.wal2json
  version: 1.0.1
