---

domain: openfoodnetwork.org.au
host_id: au-prod
rails_env: production

admin_email: maikel@openfoodnetwork.org.au

mail_domain: openfoodnetwork.org

# Optional list of subdomains to register in letsencrypt certificate
# Defaults to {{ domain }} if list is undefined
certbot_domains:
  - openfoodnetwork.org.au
  - www.openfoodnetwork.org.au
  - prod2.openfoodnetwork.org.au

# Size in bytes. You can also use units like 1G, 512MiB or 1000KB. See: `man fallocate`
# The default is `false`, not installing a swapfile.
swapfile_size: 8G

unicorn_timeout: 360
unicorn_workers: 3

# Enable external database access for third party integrations
postgres_listen_addresses:
  - '*'

custom_hba_entries:
  - { type: hostssl, database: "{{ db }}", user: zapier, address: '54.86.9.50/32', auth_method: md5 }

custom_application_env_vars: |
  OFN_FEATURE_CONNECT_AND_LEARN: "true"
