---

domain: staging.openfoodnetwork.org.uk
host_id: uk-staging
rails_env: staging

admin_email: dev.ofnuk@gmail.com

unicorn_timeout: 120

enable_rails_apm: "true" # has to be explicitly defined as a string due to some datadog bug
