---
domain: openfoodnetwork.de
rails_env: production
admin_email: admin@openfoodfoundation.org

mail_domain: openfoodnetwork.de

# Optional list of subdomains to register in letsencrypt certificate
# Defaults to {{ domain }} if list is undefined
#
#certbot_domains:
#  - example.com
#  - www.example.com
#  - info.example.com

# Size in bytes. You can also use units like 1G, 512MiB or 1000KB. See: `man fallocate`
# The default is `false`, not installing a swapfile.
swapfile_size: 2G

# Enable external database access for third party integrations
#postgres_listen_addresses:
#  - '*'
#
#custom_hba_entries:
#  - { type: hostssl, database: "{{ db }}", user: zapier, address: '54.86.9.50/32', auth_method: md5 }
