---
domain: openfoodnetwork.de
rails_env: production
admin_email: admin@openfoodfoundation.org

mail_domain: openfoodnetwork.de

certbot_domains:
  - openfoodnetwork.de
  - www.openfoodnetwork.de

# Size in bytes. You can also use units like 1G, 512MiB or 1000KB. See: `man fallocate`
# The default is `false`, not installing a swapfile.
swapfile_size: 2G

# Enable external database access for third party integrations
#postgres_listen_addresses:
#  - '*'
#
#custom_hba_entries:
#  - { type: hostssl, database: "{{ db }}", user: zapier, address: '54.86.9.50/32', auth_method: md5 }

# The server currently has 8 CPUs and 32 GB of memory.
# Since they are experimenting with thousands of products and have to
# report to the government next week (May 2019) we better keep as
# many resources as possible.
unicorn_workers: 6
unicorn_timeout: 360
