---
sudo: false
language: python
python: "2.7"

install:
  # - pip install dopy
  # - pip install httplib2
  - pip install 'ansible<2.7.0'
  - pip install ansible-lint

script:
  - bin/setup
  - ansible-playbook -i inventory/dev --syntax-check site.yml
  - ansible-playbook -i inventory/dev --syntax-check playbooks/backup.yml
  - ansible-playbook -i inventory/dev --syntax-check playbooks/deploy.yml
  - ansible-playbook -i inventory/dev --syntax-check playbooks/provision.yml
  - ansible-playbook -i inventory/dev --syntax-check playbooks/rollback.yml
  - ansible-playbook -i inventory/dev --syntax-check playbooks/setup.yml
  - ansible-playbook -i inventory/dev --syntax-check playbooks/verify.yml
  - ansible-playbook -i inventory/dev --syntax-check playbooks/development.yml
  - ansible-lint site.yml --exclude=community
