---

- name: prompt for github credentials
  include_tasks: login_prompt.yml

- name: fetch ofn-secrets
  git:
    repo: "https://{{ secrets_user | urlencode }}:{{ secrets_password | urlencode }}@github.com/openfoodfoundation/ofn-secrets.git"
    dest: "/tmp/ofn-secrets"
    version: master
    depth: 1

- name: register list of secrets files
  find:
    paths: "/tmp/ofn-secrets"
    file_type: directory
  register: fetched_secrets

- name: add secrets to host_vars
  include_tasks: update_secrets.yml
  loop: "{{ fetched_secrets.files }}"
  loop_control:
    loop_var: secrets_host_path

- name: remove temporary files
  file:
    dest: "/tmp/ofn-secrets"
    state: absent
