--- # Rollback

- name: remove current path
  file:
    dest: "{{ current_path }}"
    state: absent

- name: copy rollback repo to current path
  command: cp -r {{ rollback_path }} {{ current_path }}
  args:
    creates: "{{ current_path }}"

- name: restore database from backup
  postgresql_db:
    name: "{{ db }}"
    owner: "{{ db_user }}"
    state: restore
    target: "{{ rollback_sql_path }}"
  become: true
  become_user: postgres
  notify:
    - precompile assets
    - restart unicorn
