---
# This can be removed after all servers have been provisioned

- name: remove previously added brotli ppa (if present)
  apt_repository:
    repo: ppa:hda-me/nginx-stable
    state: absent
  register: brotli_remove_ppa
  become: yes

- name: ensure official nginx version # noqa 503
  apt:
    name: nginx=1.16.1-1*
    force: yes
  when: brotli_remove_ppa.changed
  become: yes
  notify: restart nginx
