#------------------
# Precompile assets

# Commands are wrapped in "bash -lc" so that ruby can be initialised using rbenv

# TODO make precompile conditional to speed things up.
- name: precompile assets
  command: bash -lc "bundle exec rake assets:precompile:primary RAILS_GROUPS=assets RAILS_ENV={{ rails_env }}" chdir="{{ current_path }}"
  notify: precompile nondigest assets

- name: precompile nondigest assets
  command: bash -lc "bundle exec rake assets:precompile:nondigest RAILS_GROUPS=assets RAILS_ENV={{ rails_env }}" chdir="{{ current_path }}"

- name: restart nginx
  service:
    name: nginx
    state: restarted
  become: yes
  become_user: root
