--- # Set up Ansible and restricted deployment user for deployment via Semaphore

- name: install ansible and lshell
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - ansible
      - lshell
  become: yes

- name: create lshell directory
  file:
    path: "/etc/lshell.d"
    state: directory

- name: include lshell config
  template:
    src: lshell_config.j2
    dest: "/etc/lshell.conf"

- name: create deployment user
  user:
    name: "{{ deployment_user }}"
    state: present
    append: yes
    shell: /usr/bin/lshell
  become: yes

- name: add lshell settings for deployment user
  template:
    src: lshell_deploy_user.j2
    dest: "/etc/lshell.d/{{ deployment_user }}.conf"

- name: add sudoers file
  template:
    src: sudoers.j2
    dest: "/etc/sudoers.d/{{ deployment_user }}"
    mode: 0440

- name: fetch ofn-install repo
  git:
    repo: https://github.com/openfoodfoundation/ofn-install.git
    dest: "/home/{{ deployment_user }}/ofn-install"
    version: master
    force: yes
  tags: fetch_ofn_install

- name: install community modules
  shell: "/home/{{ deployment_user }}/ofn-install/bin/setup"
  tags: update_community_modules

- name: create secure directory for keys
  file:
    path: "/home/{{ user }}/keys"
    state: directory
    owner: "{{ user }}"
    mode: 0700

- name: check certificate already exists
  stat:
    path: "/home/{{ user }}/keys/semaphore.pub"
  register: semaphore_key

- name: generate semaphore key pair
  command: "ssh-keygen -f /home/{{ user }}/keys/semaphore -t rsa -b 4096 -C semaphore -N '' "
  when: not semaphore_key.stat.exists

- name: copy public key
  shell: "cat /home/{{ user }}/keys/semaphore.pub"
  register: semaphore_public_key

- name: add semaphore public key to deployment user's authorized_keys
  authorized_key:
    user: "{{ deployment_user }}"
    key: "{{ semaphore_public_key.stdout }}"
    state: present
