--- # common

- name: update apt
  apt:
    update_cache=yes
  become: yes
  tags: packages

  #TODO remove unnecesary packages from this list.
- name: install base packages
  apt:
    pkg="{{ item }}"
    state=present
  become: yes
  with_items:
    - acl
    - build-essential
    - git-core
    - nodejs
    - imagemagick
    - curl
    - python-pycurl
    - python-psycopg2 # needed for some ansible libraries
    - python3-psycopg2
    - python-software-properties
    - libpq-dev
    - tklib
    - zlib1g-dev
    - libssl-dev
    #- libreadline-gplv2-dev
    - libxml2
    - libxml2-dev
    - libxslt1-dev
    - memcached
    - ranger
    #- fontconfig # needed for phantomjs
    #- nfs-common # make virtualbox faster
  tags: packages

# Remove monit if still installed. The notified handlers will run only once
# (when the main task triggers a change by removing the config file)
- name: clean up monit
  file:
    state: absent
    path: /etc/monit/conf.d/{{ app }}
  become: yes
  become_user: root
  notify:
    - stop monit service
    - remove monit package
