--- # common

- name: update apt
  apt:
    update_cache: yes
    cache_valid_time: 86400 # seconds = 60*60*24 seconds = 24 hours
  become: yes
  tags: packages

- name: install base packages
  apt:
    name: "{{ packages }}"
  become: yes
  vars:
    packages:
      # Ansible support
      - python-pycurl
      - python-psycopg2
      - python3-psycopg2
      - python-software-properties

      # unknown why or if needed
      # The playbooks run without these dependencies,
      # but they may be hidden run time dependencies
      # like imagemagick.
      - acl
      - nodejs
      - curl

      # build ruby and gems
      - build-essential

      # manage code
      - git-core

      # OFN dependencies
      - imagemagick
      - libpq-dev
      - zlib1g-dev
      - libssl-dev
      - libxml2
      - libxml2-dev
      - libxslt1-dev
      - memcached
  tags: packages

# Remove monit if still installed. The notified handlers will run only once
# (when the main task triggers a change by removing the config file)
- name: clean up monit
  file:
    state: absent
    path: /etc/monit/conf.d/{{ app }}
  become: yes
  become_user: root
  notify:
    - stop monit service
    - remove monit package
