--- # dbserver

- import_tasks: postgresql.yml

- name: add .pgpass file for {{ unicorn_user }}
  template:
    src: pgpass.j2
    dest: "{{ unicorn_home_path }}/.pgpass"
    owner: "{{ unicorn_user }}"
    mode: 0600
  become: yes
  become_user: "{{ unicorn_user }}"

- import_tasks: fix_template_encoding.yml
  tags: template_encoding
