--- # dbserver

- import_tasks: postgresql.yml # Install postgresql with geerlingguy.postgresql role

- name: add .pgpass file for {{ unicorn_user }}
  template:
    src: pgpass.j2
    dest: "{{ unicorn_home_path }}/.pgpass"
    owner: "{{ unicorn_user }}"
    mode: 0600
  become: yes
  become_user: "{{ unicorn_user }}"

- import_tasks: fix_template_encoding.yml
  tags: template_encoding

- name: create extensions
  become: yes
  become_user: postgres
  postgresql_ext:
    name: pg_stat_statements
    db: "{{ db }}"
