--- # dbserver

- import_tasks: postgresql.yml

- name: add .pgpass file for {{ unicorn_user }}
  template:
    src: pgpass.j2
    dest: "{{ unicorn_home_path }}/.pgpass"
    owner: "{{ unicorn_user }}"
    mode: 0600
  become: yes
  become_user: "{{ unicorn_user }}"

# Rails expects unicode databases. See the script for more details.
- name: fix postgres db encoding problem
  script: fix_pg_encoding.sh
  become: yes
  become_user: postgres
  tags:
    - pg-en
