--- # Can be simplified when https://github.com/geerlingguy/ansible-role-postgresql/pull/31 is included in a release...

- import_role:
    name: geerlingguy.postgresql

- include_role:
    name: geerlingguy.postgresql
    tasks_from: variables

- include_role:
    name: geerlingguy.postgresql
    tasks_from: initialize

- include_role:
    name: geerlingguy.postgresql
    tasks_from: configure
  vars:
    postgresql_global_config_options:
      - option: shared_preload_libraries
        value: 'pg_stat_statements'
      - option: pg_stat_statements.track
        value: all
      - option: pg_stat_statements.max
        value: 10000

- name: create extensions
  become: yes
  become_user: postgres
  postgresql_ext:
    name: pg_stat_statements
    db: "{{ db }}"

- include_role:
    name: geerlingguy.postgresql
    tasks_from: users
  vars:
    postgresql_user: postgres
    postgresql_users:
      - name: "{{ db_user }}"
        password: "{{ db_password }}"
        role_attr_flags: "{{ db_user_roles }}"

- include_role:
    name: geerlingguy.postgresql
    tasks_from: databases
  vars:
    postgresql_user: postgres
    postgresql_databases:
      - name: "{{ db }}"
        owner: "{{ db_user }}"
        login_host: "{{ db_host }}"
        login_password: "{{ db_password }}"
        lc_collate: "{{ postgres_encoding }}"
        lc_ctype: "{{ postgres_encoding }}"
