---
- name: deploy
  hosts: ofn_servers
  remote_user: "{{ user }}"
  become: yes
  become_user: "{{ unicorn_user }}"

  pre_tasks:
    - include_role:
        name: check_secrets

  roles:
    - role: deploy
