---
- name: provision
  hosts: ofn_servers
  remote_user: "{{ user }}"
  roles:
    - role: unicorn_user # Create unprivileged user to run unicorn
      tags: unicorn_user

    - role: common # Install common apps and libraries, and setup shell.
      tags: common

    - role: language # Setup locale.
      tags: language

    - role: zzet.rbenv # Install ruby. If missing run: ansible-galaxy install zzet.rbenv
      rbenv:
        env: user
        version: v1.0.0
        default_ruby: "{{ ruby_version }}"
        rubies:
          - version: "{{ ruby_version }}"

      rbenv_users:
        - "{{ unicorn_user }}"
      tags: ruby

    - role: dbserver # Set up database server and user for the app.
      tags: dbserver
      db_user_roles: SUPERUSER,CREATEDB
      db_user: ofn

  vars:
    ansible_python_interpreter: /usr/bin/python2.7
    language_packages:
      - language-pack-en-base
    language: en_US.UTF-8
    users_sysadmin: []
