---
- name: PostgreSQL production tuning
  hosts: ofn_servers
  remote_user: "{{ user }}"

  tasks:
    - name: Find current postgres version
      shell: psql postgres -c 'SHOW config_file;' | grep etc | egrep -o '[0-9]{1,}\.*[0-9]{1,}'
      become: yes
      become_user: postgres
      register: pg_current_version

    - debug:
        msg: "Postgres current version: {{ pg_current_version.stdout }}"

    - name: Create postgres conf.d directory
      file:
        dest: "/etc/postgresql/{{ pg_current_version.stdout }}/main/conf.d"
        state: directory
      become: yes

    - name: Include conf.d directory in postgresql.conf
      lineinfile:
        path: "/etc/postgresql/{{ pg_current_version.stdout }}/main/postgresql.conf"
        line: "include_dir 'conf.d'"
      become: yes

    - name: Add tuning configuration
      copy:
        content: |
          shared_buffers = {{ ( ansible_memtotal_mb / 4 ) | int }}MB
          effective_cache_size = {{ ( ( ansible_memtotal_mb / 4 ) * 3 ) | int }}MB
          maintenance_work_mem = {{ ( ansible_memtotal_mb / 16 ) | int }}MB
        dest: "/etc/postgresql/{{ pg_current_version.stdout }}/main/conf.d/tuning.conf"
      become: yes
      register: tuning_configuration
      when: remove_postgres_tuning is undefined

    - name: Optionally remove tuning configuration
      file:
        path: "/etc/postgresql/{{ pg_current_version.stdout }}/main/conf.d/tuning.conf"
        state: absent
      when: remove_postgres_tuning is defined

    - name: Reload postgres
      service:
        name: postgresql
        state: reloaded
      become: yes
      when: tuning_configuration.changed
