---
- name: provision
  hosts: ofn_servers
  remote_user: "{{ user }}"

  pre_tasks:
    - include_role:
        name: check_secrets

  roles:
    - role: ssh_keys # Add sysadmin ssh keys to server
      become: yes
      tags: ssh_keys

    - role: geerlingguy.security
      become: yes
      become_user: root
      tags: security

    - role: oefenweb.swapfile
      become: yes
      tags: swapfile

    - role: unicorn_user # Create unprivileged user to run unicorn
      tags: unicorn_user

    - role: common # Install common apps and libraries, and setup shell.
      tags: common

    - role: compatibility # Handle version-specific OS dependencies and configuration
      tags: compatibility

    - role: language # Setup locale.
      tags: language

    - role: zzet.rbenv # Install ruby. If missing run: ansible-galaxy install zzet.rbenv
      rbenv:
        env: user
        version: v1.0.0
        default_ruby: "{{ ruby_version }}"
        rubies:
          - version: "{{ ruby_version }}"

      rbenv_users:
        - "{{ unicorn_user }}"
      tags: ruby

    - role: app # Build the app directory structure and support files.
      become: yes
      become_user: "{{ unicorn_user }}"
      tags: app

    - role: dbserver # Set up database server and user for the app.
      become: yes
      become_user: root
      tags: dbserver
      db_user_roles: CREATEDB

    - role: coopdevs.certbot_nginx
      become: yes
      vars:
        domain_name: "{{ certbot_domains | default([domain]) | join(',') }}"
        letsencrypt_email: "{{ developer_email }}"
        certbot_nginx_cert_name: "{{ certbot_cert_name | default(None) }}"
      when: inventory_hostname not in groups['local']
      tags: certbot

    - role: jdauphant.nginx
      become: yes
      tags: nginx

    - role: webserver # Build the unicorn webserver.
      tags: webserver

    - role: Datadog.datadog
      become: yes
      vars:
        datadog_api_key: "{{ datadog_key }}"
      when: datadog_key is defined
      tags: datadog

  tasks:
    - name: notify slack
      slack:
        token: "T02G54U79/BF25P9F7A/DJdtYaLLUpRJPiu72d8NqgGg"
        msg: '{{ inventory_hostname }} provisioned'
        channel: "#devops-notifications"
        username: "ansible executed by {{ lookup('env','USER') }}"
      when: inventory_hostname not in groups['local']
