---
# See https://github.com/openfoodfoundation/ofn-install/wiki/Setup for more info
checkout_zone: Europe
country_code: ES
currency: EUR
locale: es
available_locales: es,ca,pt
language: es_ES.UTF-8
language_packages:
  - language-pack-es-base
l10n_repo: https://github.com/openfoodfoundation/l10n_au.git
timezone: Madrid

# Used for the LetsEncrypt email setting
developer_email: info@coopdevs.org

# Users listed here will have their key from /files/keys added to the unicorn_user
users_sysadmin:
  - enricostn
  - dani
  - pau

s3_backups_bucket: none
s3_access_key: 666
s3_secret: 666

stripe_client_id: 666
stripe_instance_secret_key: 666
